---
title: "Referencias"
author: "Mayra Lizeth Bárcenas Guevara y Mariana Gómez Becerra"
date: "2026-05-16"
output: html_document
---

# Referencias utilizadas para la escritura del código y realización de los análisis

Álvarez, R. (2024). *Dada2_Example_2024* [Software]. GitHub. <https://github.com/robertoalvarezm/Dada2_Example_2024>

Benjjneb. (2025a). *Error Rate Learning*. DeepWiki. <https://deepwiki.com/benjjneb/dada2/2.3-error-rate-learning>

Benjjneb. (2025b). *Sample Inference*. DeepWiki. <https://deepwiki.com/benjjneb/dada2/2.4-sample-inference>

Benjjneb. (2025c). *Visualization*. DeepWiki. <https://deepwiki.com/benjjneb/dada2/7-visualization#error-rate-visualization>

Callahan, B. (2024). Silva taxonomic training data formatted for DADA2 (Silva version 138.2) [Dataset]. In *Zenodo (CERN European Organization for Nuclear Research)*. <https://doi.org/10.5281/zenodo.14169026>

*DADA2 Pipeline Tutorial (1.16)*. (n.d.). <https://benjjneb.github.io/dada2/tutorial>

Quast C, Pruesse E, Yilmaz P, Gerken J, Schweer T, Yarza P, Peplies J, Glockner FO (2013) The SILVA ribosomal RNA gene database project: improved data processing and web-based tools. Nucleic Acids Research 41:D590-D596

Yilmaz P, Parfrey LW, Yarza P, Gerken J, Pruesse E, Quast C, Schweer T, Peplies J, Ludwig W, Glockner FO (2014) The SILVA and "All-species Living Tree Project (LTP)" taxonomic frameworks. Nucleic Acid Res. 42:D643-D648
